main:
  components_repository: "https://github.com/faznaimov/ml-pipeline-for-short-term-rental-prices#components"
  # All the intermediate files will be copied to this directory at the end of the run.
  # Set this to null if you are running in prod
  project_name: nyc_airbnb
  experiment_name: v1.0.0
  steps: all
etl:
  sample: "sample1.csv"
  min_price: 10 # dollars
  max_price: 350 # dollars
data_check:
  kl_threshold: 0.2
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Fix this for reproducibility, change to have new splits
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: "neighbourhood_group"
  # Maximum number of features to consider for the TFIDF applied to the title of the
  # insertion (the column called "name")
  max_tfidf_features: 5
  # export artifact name
  export_artifact: "model_export"
  # RandomForestRegressor. This is a subsample, but more could be added:
  random_forest_pipeline:
    random_forest:
      n_estimators: 100
      max_depth: 15
      min_samples_split: 4
      min_samples_leaf: 3
      # Here -1 means all available cores
      n_jobs: -1
      criterion: mae
      max_features: 0.5
      # DO not change the following
      oob_score: true
    features:
      numerical:
        - "host_id"
        - "latitude"
        - "longitude"
        - "minimum_nights"
        - "number_of_reviews"
        - "reviews_per_month"
        - "calculated_host_listings_count"
        - "availability_365"
      ordinal_categorical:
        - "room_type"
      non_ordinal_categorical:
        - "neighbourhood_group"
      nlp:
        - "name"
      date:
        - "last_review"
